use JaaamDb;
CREATE TABLE [User] (
	Id int IDENTITY(1,1) NOT NULL,
	FirstName varchar(250) NOT NULL,
	LastName varchar(250) NOT NULL,
	Username varchar(250) NOT NULL,
	Email varchar(250) NOT NULL,
	PhoneNumber varchar(250) NOT NULL,
	AccountId int NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Bet] (
	Id int IDENTITY(1,1) NOT NULL,
	Amount decimal(18,2) NOT NULL,
	Odds decimal(18,2) NOT NULL,
	Verified  bit NOT NULL DEFAULT 0, 
	UserId int NOT NULL,
  CONSTRAINT [PK_BET] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Event] (
	Id int IDENTITY(1,1) NOT NULL,
	Name varchar(250) NOT NULL,
	GameName varchar(250) NOT NULL,
	Type varchar(250) NOT NULL,
	Held bit NOT NULL DEFAULT 0
  CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Match] (
	Id int IDENTITY(1,1) NOT NULL,
	Format varchar(250) NOT NULL,
	WinnerId int,
	EventId int NOT NULL,
	Held bit NOT NULL DEFAULT 0
  CONSTRAINT [PK_MATCH] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Player] (
	Id int IDENTITY(1,1) NOT NULL,
	NickName varchar(250) NOT NULL,
	Age varchar(250) NOT NULL,
	Role varchar(250) NOT NULL,
	TeamId int,
  CONSTRAINT [PK_PLAYER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Team] (
	Id int IDENTITY(1,1) NOT NULL,
	Name varchar(250) NOT NULL,
  CONSTRAINT [PK_TEAM] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TeamsInMatch] (
	Id int IDENTITY(1,1) NOT NULL,
	TeamId int NOT NULL,
	MatchId int NOT NULL,
  CONSTRAINT [PK_TEAMSINMATCH] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BetsOnEvent] (
	Id int IDENTITY(1,1) NOT NULL,
	EventId int NOT NULL,
	BetId int NOT NULL,
  CONSTRAINT [PK_BETSONEVENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BetsOnPlayer] (
	Id int IDENTITY(1,1) NOT NULL,
	BetId int NOT NULL,
	PlayerId int NOT NULL,
  CONSTRAINT [PK_BETSONPLAYER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BetsOnTeam] (
	Id int IDENTITY(1,1) NOT NULL,
	BetId int NOT NULL,
	TeamId int NOT NULL,
  CONSTRAINT [PK_BETSONTEAM] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BetsOnMatch] (
	Id int IDENTITY(1,1) NOT NULL,
	MatchId int NOT NULL,
	BetId int NOT NULL,
  CONSTRAINT [PK_BETSONMATCH] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Account] (
	Id int IDENTITY(1,1) NOT NULL,
	Balance decimal(18,2) NOT NULL,
  CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Map] (
	Id int IDENTITY(1,1) NOT NULL,
	Name varchar(250) NOT NULL UNIQUE,
	IsActive bit NOT NULL,
  CONSTRAINT [PK_MAP] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [MapsOnMatch] (
	Id int IDENTITY(1,1) NOT NULL,
	MatchId int NOT NULL,
	MapId int NOT NULL,
  CONSTRAINT [PK_MAPSONMATCH] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [TeamsOnBetsOnMatch] (
	Id int IDENTITY(1,1) NOT NULL,
	TeamId int NOT NULL,
	BomId int NOT NULL,
  CONSTRAINT [PK_TEAMSONBETSONMATCH] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk0] FOREIGN KEY ([AccountId]) REFERENCES [Account]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk0]
GO

ALTER TABLE [Bet] WITH CHECK ADD CONSTRAINT [Bet_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Bet] CHECK CONSTRAINT [Bet_fk0]
GO


ALTER TABLE [Match] WITH CHECK ADD CONSTRAINT [Match_fk0] FOREIGN KEY ([EventId]) REFERENCES [Event]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Match] CHECK CONSTRAINT [Match_fk0]
GO

ALTER TABLE [Player] WITH CHECK ADD CONSTRAINT [Player_fk0] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Player] CHECK CONSTRAINT [Player_fk0]
GO


ALTER TABLE [TeamsInMatch] WITH CHECK ADD CONSTRAINT [TeamsInMatch_fk0] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [TeamsInMatch] CHECK CONSTRAINT [TeamsInMatch_fk0]
GO
ALTER TABLE [TeamsInMatch] WITH CHECK ADD CONSTRAINT [TeamsInMatch_fk1] FOREIGN KEY ([MatchId]) REFERENCES [Match]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [TeamsInMatch] CHECK CONSTRAINT [TeamsInMatch_fk1]
GO

ALTER TABLE [BetsOnEvent] WITH CHECK ADD CONSTRAINT [BetsOnEvent_fk0] FOREIGN KEY ([EventId]) REFERENCES [Event]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnEvent] CHECK CONSTRAINT [BetsOnEvent_fk0]
GO
ALTER TABLE [BetsOnEvent] WITH CHECK ADD CONSTRAINT [BetsOnEvent_fk1] FOREIGN KEY ([BetId]) REFERENCES [Bet]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnEvent] CHECK CONSTRAINT [BetsOnEvent_fk1]
GO

ALTER TABLE [BetsOnPlayer] WITH CHECK ADD CONSTRAINT [BetsOnPlayer_fk0] FOREIGN KEY ([BetId]) REFERENCES [Bet]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnPlayer] CHECK CONSTRAINT [BetsOnPlayer_fk0]
GO
ALTER TABLE [BetsOnPlayer] WITH CHECK ADD CONSTRAINT [BetsOnPlayer_fk1] FOREIGN KEY ([PlayerId]) REFERENCES [Player]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnPlayer] CHECK CONSTRAINT [BetsOnPlayer_fk1]
GO

ALTER TABLE [BetsOnTeam] WITH CHECK ADD CONSTRAINT [BetsOnTeam_fk0] FOREIGN KEY ([BetId]) REFERENCES [Bet]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnTeam] CHECK CONSTRAINT [BetsOnTeam_fk0]
GO
ALTER TABLE [BetsOnTeam] WITH CHECK ADD CONSTRAINT [BetsOnTeam_fk1] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnTeam] CHECK CONSTRAINT [BetsOnTeam_fk1]
GO

ALTER TABLE [BetsOnMatch] WITH CHECK ADD CONSTRAINT [BetsOnMatch_fk0] FOREIGN KEY ([MatchId]) REFERENCES [Match]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnMatch] CHECK CONSTRAINT [BetsOnMatch_fk0]
GO
ALTER TABLE [BetsOnMatch] WITH CHECK ADD CONSTRAINT [BetsOnMatch_fk1] FOREIGN KEY ([BetId]) REFERENCES [Bet]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [BetsOnMatch] CHECK CONSTRAINT [BetsOnMatch_fk1]
GO
ALTER TABLE [MapsOnMatch] WITH CHECK ADD CONSTRAINT [MapsOnMatch_fk0] FOREIGN KEY ([MatchId]) REFERENCES [Match]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [MapsOnMatch] CHECK CONSTRAINT [MapsOnMatch_fk0]
GO
ALTER TABLE [MapsOnMatch] WITH CHECK ADD CONSTRAINT [MapsOnMatch_fk1] FOREIGN KEY ([MapId]) REFERENCES [Map]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [MapsOnMatch] CHECK CONSTRAINT [MapsOnMatch_fk1]
GO
ALTER TABLE [TeamsOnBetsOnMatch] WITH CHECK ADD CONSTRAINT [TeamsOnBetsOnMatch_fk0] FOREIGN KEY ([TeamId]) REFERENCES [Team]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [TeamsOnBetsOnMatch] CHECK CONSTRAINT [TeamsOnBetsOnMatch_fk0]
GO
ALTER TABLE [TeamsOnBetsOnMatch] WITH CHECK ADD CONSTRAINT [TeamsOnBetsOnMatch_fk1] FOREIGN KEY ([BomId]) REFERENCES [BetsOnMatch]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [TeamsOnBetsOnMatch] CHECK CONSTRAINT [TeamsOnBetsOnMatch_fk1]
GO

