//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAAAM_WebClient.WCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Betable", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JAAAM_WebClient.WCFService.Match))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JAAAM_WebClient.WCFService.Team))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JAAAM_WebClient.WCFService.Event))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(JAAAM_WebClient.WCFService.Player))]
    public partial class Betable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Match : JAAAM_WebClient.WCFService.Betable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HeldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Map[] MapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Team[] TeamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Team WinnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Format {
            get {
                return this.FormatField;
            }
            set {
                if ((object.ReferenceEquals(this.FormatField, value) != true)) {
                    this.FormatField = value;
                    this.RaisePropertyChanged("Format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Held {
            get {
                return this.HeldField;
            }
            set {
                if ((this.HeldField.Equals(value) != true)) {
                    this.HeldField = value;
                    this.RaisePropertyChanged("Held");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Map[] Maps {
            get {
                return this.MapsField;
            }
            set {
                if ((object.ReferenceEquals(this.MapsField, value) != true)) {
                    this.MapsField = value;
                    this.RaisePropertyChanged("Maps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Team[] Teams {
            get {
                return this.TeamsField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamsField, value) != true)) {
                    this.TeamsField = value;
                    this.RaisePropertyChanged("Teams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Team Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Team", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Team : JAAAM_WebClient.WCFService.Betable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Player[] PlayersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Player[] Players {
            get {
                return this.PlayersField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersField, value) != true)) {
                    this.PlayersField = value;
                    this.RaisePropertyChanged("Players");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Event : JAAAM_WebClient.WCFService.Betable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HeldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Match[] MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameName {
            get {
                return this.GameNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GameNameField, value) != true)) {
                    this.GameNameField = value;
                    this.RaisePropertyChanged("GameName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Held {
            get {
                return this.HeldField;
            }
            set {
                if ((this.HeldField.Equals(value) != true)) {
                    this.HeldField = value;
                    this.RaisePropertyChanged("Held");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Match[] Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Player : JAAAM_WebClient.WCFService.Betable {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamId {
            get {
                return this.TeamIdField;
            }
            set {
                if ((this.TeamIdField.Equals(value) != true)) {
                    this.TeamIdField = value;
                    this.RaisePropertyChanged("TeamId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Map", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Map : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Bet[] BetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Bet[] Bets {
            get {
                return this.BetsField;
            }
            set {
                if ((object.ReferenceEquals(this.BetsField, value) != true)) {
                    this.BetsField = value;
                    this.RaisePropertyChanged("Bets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bet", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Bet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OddsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Betable TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Team WinConditionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Odds {
            get {
                return this.OddsField;
            }
            set {
                if ((this.OddsField.Equals(value) != true)) {
                    this.OddsField = value;
                    this.RaisePropertyChanged("Odds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Betable Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Verified {
            get {
                return this.VerifiedField;
            }
            set {
                if ((this.VerifiedField.Equals(value) != true)) {
                    this.VerifiedField = value;
                    this.RaisePropertyChanged("Verified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Team WinCondition {
            get {
                return this.WinConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.WinConditionField, value) != true)) {
                    this.WinConditionField = value;
                    this.RaisePropertyChanged("WinCondition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kill", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Kill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KilledNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KillerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KilledName {
            get {
                return this.KilledNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KilledNameField, value) != true)) {
                    this.KilledNameField = value;
                    this.RaisePropertyChanged("KilledName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KillerName {
            get {
                return this.KillerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KillerNameField, value) != true)) {
                    this.KillerNameField = value;
                    this.RaisePropertyChanged("KillerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Odds", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Odds : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Match MatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Odds1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Odds2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Match Match {
            get {
                return this.MatchField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchField, value) != true)) {
                    this.MatchField = value;
                    this.RaisePropertyChanged("Match");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Odds1 {
            get {
                return this.Odds1Field;
            }
            set {
                if ((this.Odds1Field.Equals(value) != true)) {
                    this.Odds1Field = value;
                    this.RaisePropertyChanged("Odds1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Odds2 {
            get {
                return this.Odds2Field;
            }
            set {
                if ((this.Odds2Field.Equals(value) != true)) {
                    this.Odds2Field = value;
                    this.RaisePropertyChanged("Odds2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Round", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Round : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Kill[] KillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Match MatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamOneScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeamTwoScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JAAAM_WebClient.WCFService.Team WinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerSideField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Kill[] Kills {
            get {
                return this.KillsField;
            }
            set {
                if ((object.ReferenceEquals(this.KillsField, value) != true)) {
                    this.KillsField = value;
                    this.RaisePropertyChanged("Kills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Match Match {
            get {
                return this.MatchField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchField, value) != true)) {
                    this.MatchField = value;
                    this.RaisePropertyChanged("Match");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamOneScore {
            get {
                return this.TeamOneScoreField;
            }
            set {
                if ((this.TeamOneScoreField.Equals(value) != true)) {
                    this.TeamOneScoreField = value;
                    this.RaisePropertyChanged("TeamOneScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeamTwoScore {
            get {
                return this.TeamTwoScoreField;
            }
            set {
                if ((this.TeamTwoScoreField.Equals(value) != true)) {
                    this.TeamTwoScoreField = value;
                    this.RaisePropertyChanged("TeamTwoScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JAAAM_WebClient.WCFService.Team Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerSide {
            get {
                return this.WinnerSideField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerSideField, value) != true)) {
                    this.WinnerSideField = value;
                    this.RaisePropertyChanged("WinnerSide");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePlayer", ReplyAction="http://tempuri.org/IService/CreatePlayerResponse")]
        int CreatePlayer(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreatePlayer", ReplyAction="http://tempuri.org/IService/CreatePlayerResponse")]
        System.Threading.Tasks.Task<int> CreatePlayerAsync(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlayer", ReplyAction="http://tempuri.org/IService/GetPlayerResponse")]
        JAAAM_WebClient.WCFService.Player GetPlayer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlayer", ReplyAction="http://tempuri.org/IService/GetPlayerResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Player> GetPlayerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePlayer", ReplyAction="http://tempuri.org/IService/DeletePlayerResponse")]
        void DeletePlayer(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePlayer", ReplyAction="http://tempuri.org/IService/DeletePlayerResponse")]
        System.Threading.Tasks.Task DeletePlayerAsync(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPlayer", ReplyAction="http://tempuri.org/IService/EditPlayerResponse")]
        void EditPlayer(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditPlayer", ReplyAction="http://tempuri.org/IService/EditPlayerResponse")]
        System.Threading.Tasks.Task EditPlayerAsync(JAAAM_WebClient.WCFService.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlayers", ReplyAction="http://tempuri.org/IService/GetPlayersResponse")]
        JAAAM_WebClient.WCFService.Player[] GetPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPlayers", ReplyAction="http://tempuri.org/IService/GetPlayersResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Player[]> GetPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMap", ReplyAction="http://tempuri.org/IService/CreateMapResponse")]
        int CreateMap(JAAAM_WebClient.WCFService.Map map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMap", ReplyAction="http://tempuri.org/IService/CreateMapResponse")]
        System.Threading.Tasks.Task<int> CreateMapAsync(JAAAM_WebClient.WCFService.Map map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMatch", ReplyAction="http://tempuri.org/IService/CreateMatchResponse")]
        int CreateMatch(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateMatch", ReplyAction="http://tempuri.org/IService/CreateMatchResponse")]
        System.Threading.Tasks.Task<int> CreateMatchAsync(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMatch", ReplyAction="http://tempuri.org/IService/GetMatchResponse")]
        JAAAM_WebClient.WCFService.Match GetMatch(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMatch", ReplyAction="http://tempuri.org/IService/GetMatchResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Match> GetMatchAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMatch", ReplyAction="http://tempuri.org/IService/EditMatchResponse")]
        void EditMatch(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMatch", ReplyAction="http://tempuri.org/IService/EditMatchResponse")]
        System.Threading.Tasks.Task EditMatchAsync(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMatch", ReplyAction="http://tempuri.org/IService/DeleteMatchResponse")]
        void DeleteMatch(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteMatch", ReplyAction="http://tempuri.org/IService/DeleteMatchResponse")]
        System.Threading.Tasks.Task DeleteMatchAsync(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMatches", ReplyAction="http://tempuri.org/IService/GetMatchesResponse")]
        JAAAM_WebClient.WCFService.Match[] GetMatches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMatches", ReplyAction="http://tempuri.org/IService/GetMatchesResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Match[]> GetMatchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaps", ReplyAction="http://tempuri.org/IService/GetMapsResponse")]
        JAAAM_WebClient.WCFService.Map[] GetMaps();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMaps", ReplyAction="http://tempuri.org/IService/GetMapsResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Map[]> GetMapsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMap", ReplyAction="http://tempuri.org/IService/EditMapResponse")]
        void EditMap(JAAAM_WebClient.WCFService.Map map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditMap", ReplyAction="http://tempuri.org/IService/EditMapResponse")]
        System.Threading.Tasks.Task EditMapAsync(JAAAM_WebClient.WCFService.Map map);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEvent", ReplyAction="http://tempuri.org/IService/CreateEventResponse")]
        int CreateEvent(JAAAM_WebClient.WCFService.Event eventObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateEvent", ReplyAction="http://tempuri.org/IService/CreateEventResponse")]
        System.Threading.Tasks.Task<int> CreateEventAsync(JAAAM_WebClient.WCFService.Event eventObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEvent", ReplyAction="http://tempuri.org/IService/GetEventResponse")]
        JAAAM_WebClient.WCFService.Event GetEvent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEvent", ReplyAction="http://tempuri.org/IService/GetEventResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Event> GetEventAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditEvent", ReplyAction="http://tempuri.org/IService/EditEventResponse")]
        void EditEvent(JAAAM_WebClient.WCFService.Event eventObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditEvent", ReplyAction="http://tempuri.org/IService/EditEventResponse")]
        System.Threading.Tasks.Task EditEventAsync(JAAAM_WebClient.WCFService.Event eventObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteEvent", ReplyAction="http://tempuri.org/IService/DeleteEventResponse")]
        void DeleteEvent(JAAAM_WebClient.WCFService.Event eventToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteEvent", ReplyAction="http://tempuri.org/IService/DeleteEventResponse")]
        System.Threading.Tasks.Task DeleteEventAsync(JAAAM_WebClient.WCFService.Event eventToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEvents", ReplyAction="http://tempuri.org/IService/GetEventsResponse")]
        JAAAM_WebClient.WCFService.Event[] GetEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetEvents", ReplyAction="http://tempuri.org/IService/GetEventsResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Event[]> GetEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTeam", ReplyAction="http://tempuri.org/IService/CreateTeamResponse")]
        int CreateTeam(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateTeam", ReplyAction="http://tempuri.org/IService/CreateTeamResponse")]
        System.Threading.Tasks.Task<int> CreateTeamAsync(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTeam", ReplyAction="http://tempuri.org/IService/GetTeamResponse")]
        JAAAM_WebClient.WCFService.Team GetTeam(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTeam", ReplyAction="http://tempuri.org/IService/GetTeamResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Team> GetTeamAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTeam", ReplyAction="http://tempuri.org/IService/EditTeamResponse")]
        void EditTeam(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EditTeam", ReplyAction="http://tempuri.org/IService/EditTeamResponse")]
        System.Threading.Tasks.Task EditTeamAsync(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTeam", ReplyAction="http://tempuri.org/IService/DeleteTeamResponse")]
        void DeleteTeam(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteTeam", ReplyAction="http://tempuri.org/IService/DeleteTeamResponse")]
        System.Threading.Tasks.Task DeleteTeamAsync(JAAAM_WebClient.WCFService.Team team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTeams", ReplyAction="http://tempuri.org/IService/GetTeamsResponse")]
        JAAAM_WebClient.WCFService.Team[] GetTeams();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTeams", ReplyAction="http://tempuri.org/IService/GetTeamsResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Team[]> GetTeamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        void CreateUser(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateUser", ReplyAction="http://tempuri.org/IService/CreateUserResponse")]
        System.Threading.Tasks.Task CreateUserAsync(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
        JAAAM_WebClient.WCFService.User GetUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User> GetUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        JAAAM_WebClient.WCFService.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        void DeleteUser(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeleteUser", ReplyAction="http://tempuri.org/IService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
        void UpdateUser(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateUser", ReplyAction="http://tempuri.org/IService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAccount", ReplyAction="http://tempuri.org/IService/UpdateAccountResponse")]
        void UpdateAccount(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpdateAccount", ReplyAction="http://tempuri.org/IService/UpdateAccountResponse")]
        System.Threading.Tasks.Task UpdateAccountAsync(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddBetToUser", ReplyAction="http://tempuri.org/IService/AddBetToUserResponse")]
        bool AddBetToUser(JAAAM_WebClient.WCFService.User user, JAAAM_WebClient.WCFService.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddBetToUser", ReplyAction="http://tempuri.org/IService/AddBetToUserResponse")]
        System.Threading.Tasks.Task<bool> AddBetToUserAsync(JAAAM_WebClient.WCFService.User user, JAAAM_WebClient.WCFService.Bet bet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBets", ReplyAction="http://tempuri.org/IService/GetBetsResponse")]
        JAAAM_WebClient.WCFService.Bet[] GetBets(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBets", ReplyAction="http://tempuri.org/IService/GetBetsResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Bet[]> GetBetsAsync(JAAAM_WebClient.WCFService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBetsOnUserOnMatch", ReplyAction="http://tempuri.org/IService/GetBetsOnUserOnMatchResponse")]
        JAAAM_WebClient.WCFService.User[] GetBetsOnUserOnMatch(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBetsOnUserOnMatch", ReplyAction="http://tempuri.org/IService/GetBetsOnUserOnMatchResponse")]
        System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User[]> GetBetsOnUserOnMatchAsync(JAAAM_WebClient.WCFService.Match match);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FakeMethodeToMakeKillOddsRoundAvalibleThroughService", ReplyAction="http://tempuri.org/IService/FakeMethodeToMakeKillOddsRoundAvalibleThroughServiceR" +
            "esponse")]
        void FakeMethodeToMakeKillOddsRoundAvalibleThroughService(JAAAM_WebClient.WCFService.Kill kill, JAAAM_WebClient.WCFService.Odds odds, JAAAM_WebClient.WCFService.Round round);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FakeMethodeToMakeKillOddsRoundAvalibleThroughService", ReplyAction="http://tempuri.org/IService/FakeMethodeToMakeKillOddsRoundAvalibleThroughServiceR" +
            "esponse")]
        System.Threading.Tasks.Task FakeMethodeToMakeKillOddsRoundAvalibleThroughServiceAsync(JAAAM_WebClient.WCFService.Kill kill, JAAAM_WebClient.WCFService.Odds odds, JAAAM_WebClient.WCFService.Round round);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : JAAAM_WebClient.WCFService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<JAAAM_WebClient.WCFService.IService>, JAAAM_WebClient.WCFService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreatePlayer(JAAAM_WebClient.WCFService.Player player) {
            return base.Channel.CreatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> CreatePlayerAsync(JAAAM_WebClient.WCFService.Player player) {
            return base.Channel.CreatePlayerAsync(player);
        }
        
        public JAAAM_WebClient.WCFService.Player GetPlayer(int id) {
            return base.Channel.GetPlayer(id);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Player> GetPlayerAsync(int id) {
            return base.Channel.GetPlayerAsync(id);
        }
        
        public void DeletePlayer(JAAAM_WebClient.WCFService.Player player) {
            base.Channel.DeletePlayer(player);
        }
        
        public System.Threading.Tasks.Task DeletePlayerAsync(JAAAM_WebClient.WCFService.Player player) {
            return base.Channel.DeletePlayerAsync(player);
        }
        
        public void EditPlayer(JAAAM_WebClient.WCFService.Player player) {
            base.Channel.EditPlayer(player);
        }
        
        public System.Threading.Tasks.Task EditPlayerAsync(JAAAM_WebClient.WCFService.Player player) {
            return base.Channel.EditPlayerAsync(player);
        }
        
        public JAAAM_WebClient.WCFService.Player[] GetPlayers() {
            return base.Channel.GetPlayers();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Player[]> GetPlayersAsync() {
            return base.Channel.GetPlayersAsync();
        }
        
        public int CreateMap(JAAAM_WebClient.WCFService.Map map) {
            return base.Channel.CreateMap(map);
        }
        
        public System.Threading.Tasks.Task<int> CreateMapAsync(JAAAM_WebClient.WCFService.Map map) {
            return base.Channel.CreateMapAsync(map);
        }
        
        public int CreateMatch(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.CreateMatch(match);
        }
        
        public System.Threading.Tasks.Task<int> CreateMatchAsync(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.CreateMatchAsync(match);
        }
        
        public JAAAM_WebClient.WCFService.Match GetMatch(int id) {
            return base.Channel.GetMatch(id);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Match> GetMatchAsync(int id) {
            return base.Channel.GetMatchAsync(id);
        }
        
        public void EditMatch(JAAAM_WebClient.WCFService.Match match) {
            base.Channel.EditMatch(match);
        }
        
        public System.Threading.Tasks.Task EditMatchAsync(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.EditMatchAsync(match);
        }
        
        public void DeleteMatch(JAAAM_WebClient.WCFService.Match match) {
            base.Channel.DeleteMatch(match);
        }
        
        public System.Threading.Tasks.Task DeleteMatchAsync(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.DeleteMatchAsync(match);
        }
        
        public JAAAM_WebClient.WCFService.Match[] GetMatches() {
            return base.Channel.GetMatches();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Match[]> GetMatchesAsync() {
            return base.Channel.GetMatchesAsync();
        }
        
        public JAAAM_WebClient.WCFService.Map[] GetMaps() {
            return base.Channel.GetMaps();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Map[]> GetMapsAsync() {
            return base.Channel.GetMapsAsync();
        }
        
        public void EditMap(JAAAM_WebClient.WCFService.Map map) {
            base.Channel.EditMap(map);
        }
        
        public System.Threading.Tasks.Task EditMapAsync(JAAAM_WebClient.WCFService.Map map) {
            return base.Channel.EditMapAsync(map);
        }
        
        public int CreateEvent(JAAAM_WebClient.WCFService.Event eventObject) {
            return base.Channel.CreateEvent(eventObject);
        }
        
        public System.Threading.Tasks.Task<int> CreateEventAsync(JAAAM_WebClient.WCFService.Event eventObject) {
            return base.Channel.CreateEventAsync(eventObject);
        }
        
        public JAAAM_WebClient.WCFService.Event GetEvent(int id) {
            return base.Channel.GetEvent(id);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Event> GetEventAsync(int id) {
            return base.Channel.GetEventAsync(id);
        }
        
        public void EditEvent(JAAAM_WebClient.WCFService.Event eventObject) {
            base.Channel.EditEvent(eventObject);
        }
        
        public System.Threading.Tasks.Task EditEventAsync(JAAAM_WebClient.WCFService.Event eventObject) {
            return base.Channel.EditEventAsync(eventObject);
        }
        
        public void DeleteEvent(JAAAM_WebClient.WCFService.Event eventToDelete) {
            base.Channel.DeleteEvent(eventToDelete);
        }
        
        public System.Threading.Tasks.Task DeleteEventAsync(JAAAM_WebClient.WCFService.Event eventToDelete) {
            return base.Channel.DeleteEventAsync(eventToDelete);
        }
        
        public JAAAM_WebClient.WCFService.Event[] GetEvents() {
            return base.Channel.GetEvents();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Event[]> GetEventsAsync() {
            return base.Channel.GetEventsAsync();
        }
        
        public int CreateTeam(JAAAM_WebClient.WCFService.Team team) {
            return base.Channel.CreateTeam(team);
        }
        
        public System.Threading.Tasks.Task<int> CreateTeamAsync(JAAAM_WebClient.WCFService.Team team) {
            return base.Channel.CreateTeamAsync(team);
        }
        
        public JAAAM_WebClient.WCFService.Team GetTeam(int id) {
            return base.Channel.GetTeam(id);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Team> GetTeamAsync(int id) {
            return base.Channel.GetTeamAsync(id);
        }
        
        public void EditTeam(JAAAM_WebClient.WCFService.Team team) {
            base.Channel.EditTeam(team);
        }
        
        public System.Threading.Tasks.Task EditTeamAsync(JAAAM_WebClient.WCFService.Team team) {
            return base.Channel.EditTeamAsync(team);
        }
        
        public void DeleteTeam(JAAAM_WebClient.WCFService.Team team) {
            base.Channel.DeleteTeam(team);
        }
        
        public System.Threading.Tasks.Task DeleteTeamAsync(JAAAM_WebClient.WCFService.Team team) {
            return base.Channel.DeleteTeamAsync(team);
        }
        
        public JAAAM_WebClient.WCFService.Team[] GetTeams() {
            return base.Channel.GetTeams();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Team[]> GetTeamsAsync() {
            return base.Channel.GetTeamsAsync();
        }
        
        public void CreateUser(JAAAM_WebClient.WCFService.User user) {
            base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task CreateUserAsync(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.CreateUserAsync(user);
        }
        
        public JAAAM_WebClient.WCFService.User GetUser(int id) {
            return base.Channel.GetUser(id);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User> GetUserAsync(int id) {
            return base.Channel.GetUserAsync(id);
        }
        
        public JAAAM_WebClient.WCFService.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public void DeleteUser(JAAAM_WebClient.WCFService.User user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void UpdateUser(JAAAM_WebClient.WCFService.User user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void UpdateAccount(JAAAM_WebClient.WCFService.User user) {
            base.Channel.UpdateAccount(user);
        }
        
        public System.Threading.Tasks.Task UpdateAccountAsync(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.UpdateAccountAsync(user);
        }
        
        public bool AddBetToUser(JAAAM_WebClient.WCFService.User user, JAAAM_WebClient.WCFService.Bet bet) {
            return base.Channel.AddBetToUser(user, bet);
        }
        
        public System.Threading.Tasks.Task<bool> AddBetToUserAsync(JAAAM_WebClient.WCFService.User user, JAAAM_WebClient.WCFService.Bet bet) {
            return base.Channel.AddBetToUserAsync(user, bet);
        }
        
        public JAAAM_WebClient.WCFService.Bet[] GetBets(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.GetBets(user);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.Bet[]> GetBetsAsync(JAAAM_WebClient.WCFService.User user) {
            return base.Channel.GetBetsAsync(user);
        }
        
        public JAAAM_WebClient.WCFService.User[] GetBetsOnUserOnMatch(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.GetBetsOnUserOnMatch(match);
        }
        
        public System.Threading.Tasks.Task<JAAAM_WebClient.WCFService.User[]> GetBetsOnUserOnMatchAsync(JAAAM_WebClient.WCFService.Match match) {
            return base.Channel.GetBetsOnUserOnMatchAsync(match);
        }
        
        public void FakeMethodeToMakeKillOddsRoundAvalibleThroughService(JAAAM_WebClient.WCFService.Kill kill, JAAAM_WebClient.WCFService.Odds odds, JAAAM_WebClient.WCFService.Round round) {
            base.Channel.FakeMethodeToMakeKillOddsRoundAvalibleThroughService(kill, odds, round);
        }
        
        public System.Threading.Tasks.Task FakeMethodeToMakeKillOddsRoundAvalibleThroughServiceAsync(JAAAM_WebClient.WCFService.Kill kill, JAAAM_WebClient.WCFService.Odds odds, JAAAM_WebClient.WCFService.Round round) {
            return base.Channel.FakeMethodeToMakeKillOddsRoundAvalibleThroughServiceAsync(kill, odds, round);
        }
    }
}
